using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NeuralNet.src
{
    class conv
    {
        public void shallow() { 
        }

        public void basic_conv() { 
        }

        public void omit_FC() { 
        }

        public void dbl_conv() { 
        }

        // Some subsequent functions may make use of the expanded MNIST
        // data.  That can be generated by running expand_mnist.py.
        public void expanded_data() { 
        }

        public void expanded_data_double_fc() { 
        }

        public void double_fc_dropout() { 
        }

        public void ensemble() { 
        }

        public void plot_errors() { 
        }

        public void plot_filters() { 
        }

        public void run_experiments() { 
        }
    }
}
